# Generated by Django 3.2 on 2023-02-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_alter_imgstore_img_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgstore',
            name='img_content',
        ),
    ]
