# Generated by Django 3.2 on 2023-02-22 05:54

import detect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_remove_imgstore_img_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgstore',
            name='img_content',
            field=models.ImageField(blank=True, help_text='图像内容', null=True, upload_to=detect.djangomodels.image_dir_path),
        ),
    ]
