# Generated by Django 3.2 on 2023-02-22 09:33

import detect.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0005_auto_20230222_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgCompareResultV',
            fields=[
                ('img_compare_id', models.AutoField(help_text='图片ID', primary_key=True, serialize=False)),
                ('img_src_id', models.IntegerField(verbose_name='源图片ID')),
                ('img_dst_id', models.IntegerField(verbose_name='对比图片ID')),
                ('plane_no_src', models.CharField(help_text='源架次', max_length=100)),
                ('plane_no_dst', models.CharField(help_text='对比架次', max_length=100)),
                ('part_no', models.CharField(help_text='组件图号', max_length=100)),
                ('result_img', models.ImageField(blank=True, help_text='图像对比结果', null=True, upload_to=detect.models.image_dir_path)),
                ('diff_count', models.IntegerField(verbose_name='比对差异数量')),
                ('compare_result', models.BinaryField(help_text='对比结果', max_length=52428800)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'img_compare_result_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImgCompareResult',
            fields=[
                ('img_compare_id', models.AutoField(help_text='图片ID', primary_key=True, serialize=False)),
                ('img_src_id', models.IntegerField(verbose_name='源图片ID')),
                ('img_dst_id', models.IntegerField(verbose_name='对比图片ID')),
                ('result_img', models.ImageField(blank=True, help_text='图像对比结果', null=True, upload_to=detect.models.image_dir_path)),
                ('diff_count', models.IntegerField(verbose_name='比对差异数量')),
                ('compare_result', models.BinaryField(help_text='对比结果', max_length=52428800)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'img_compare_result',
            },
        ),
    ]
