# Generated by Django 3.2 on 2023-02-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0006_imgcompareresult_imgcompareresultv'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgstore',
            name='is_basic_img',
            field=models.BooleanField(default=True, verbose_name='是否为基准图像'),
        ),
    ]
