# Generated by Django 3.2 on 2023-02-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0007_imgstore_is_basic_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgstore',
            name='compare_status',
            field=models.CharField(default='未对比', max_length=10, verbose_name='对比状态'),
        ),
    ]
