# Generated by Django 3.2 on 2023-02-24 01:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0010_auto_20230224_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysdict',
            name='dict_index',
        ),
        migrations.RemoveField(
            model_name='sysdict',
            name='dict_label',
        ),
        migrations.RemoveField(
            model_name='sysdict',
            name='dict_value',
        ),
        migrations.AlterField(
            model_name='sysdict',
            name='dict_name_en',
            field=models.CharField(max_length=50, verbose_name='字典英文名'),
        ),
        migrations.CreateModel(
            name='SysDictItem',
            fields=[
                ('dict_item_id', models.AutoField(help_text='字典条目ID', primary_key=True, serialize=False)),
                ('dict_value', models.CharField(max_length=50, verbose_name='字典数值')),
                ('dict_label', models.CharField(max_length=50, verbose_name='字典文本')),
                ('dict_index', models.IntegerField(verbose_name='排序位置')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('dict_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='detect.sysdict')),
            ],
            options={
                'db_table': 'sys_dict_item',
            },
        ),
    ]
