# Generated by Django 4.1.7 on 2023-03-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0011_auto_20230224_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysdict',
            options={'verbose_name': '系统字典', 'verbose_name_plural': '系统字典管理'},
        ),
        migrations.AlterModelOptions(
            name='sysdictitem',
            options={'verbose_name': '字典条目', 'verbose_name_plural': '字典条目管理'},
        ),
    ]
